services:
  back_app:
    build:
      context: ./back_app
      dockerfile: Dockerfile
    container_name: back_app
    ports:
      - "8080:8080"
    
  frontend:
    container_name: front
    build:
      context: ./list_web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always